#!/bin/sh

openslp_pkgdir="${ENCAP_SOURCE}/${ENCAP_PKGNAME}"

if [ ! -d "${ENCAP_TARGET}/etc/rc.d" ]; then
	echo "creating directory: ${ENCAP_TARGET}/etc/rc.d"
	mkdir -p "${ENCAP_TARGET}/etc/rc.d"
fi

if [ ! -f "${ENCAP_TARGET}/etc/slp.conf" ]; then
	echo "installing: ${ENCAP_TARGET}/etc/slp.conf"
	cp "${openslp_pkgdir}/etc/slp.conf" "${ENCAP_TARGET}/etc/slp.conf"
fi

if [ ! -f "${ENCAP_TARGET}/etc/slp.reg" ]; then
	echo "installing: ${ENCAP_TARGET}/etc/slp.reg"
	cp "${openslp_pkgdir}/etc/slp.reg" "${ENCAP_TARGET}/etc/slp.reg"
fi

if [ ! -f "${ENCAP_TARGET}/etc/slp.spi" ]; then
	echo "installing: ${ENCAP_TARGET}/etc/slp.spi"
	cp "${openslp_pkgdir}/etc/slp.spi" "${ENCAP_TARGET}/etc/slp.spi"
fi

if [ ! -f "${ENCAP_TARGET}/etc/rc.d/slpd" ]; then
	echo "installing: ${ENCAP_TARGET}/etc/rc.d/slpd"
	sed -e "s,@ENCAP_TARGET@,${ENCAP_TARGET},g" \
		"${openslp_pkgdir}/etc/rc.d/slpd.in" \
		> "${ENCAP_TARGET}/etc/rc.d/slpd"
	chmod +x "${ENCAP_TARGET}/etc/rc.d/slpd"
fi
