#!/bin/sh

if [ ! -d "${ENCAP_TARGET}/etc/pam.d" ]; then
	echo "creating directory: ${ENCAP_TARGET}/etc/pam.d"
	mkdir -p "${ENCAP_TARGET}/etc/pam.d"
fi

if [ ! -d "${ENCAP_TARGET}/lib/security" ]; then
	echo "creating directory: ${ENCAP_TARGET}/lib/security"
	mkdir -p "${ENCAP_TARGET}/lib/security"
fi
