#!/bin/sh

if [ ! -d "${ENCAP_TARGET}/etc/sasl2" ]; then
	echo "creating directory: ${ENCAP_TARGET}/etc/sasl2"
	mkdir -p "${ENCAP_TARGET}/etc/sasl2"
fi

if [ ! -d "${ENCAP_TARGET}/lib/sasl2" ]; then
	echo "creating directory: ${ENCAP_TARGET}/lib/sasl2"
	mkdir -p "${ENCAP_TARGET}/lib/sasl2"
fi
