# Copyright (c) 2012, Johnny C. Lam
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

########
# test #
########

pecan_action_registry="${pecan_action_registry} test"

pecan_test_vars()
{
	pecan_test_require="build"

	: ${pecan_test_style=}

	# make
	: ${pecan_test_target:=check}
}

pecan_test_deferred_vars()
{
	: ${pecan_test_srcdir=${pecan_build_srcdir}}

	case "${pecan_test_style}" in
	make)	pecan_test_default=pecan_make_test_default ;;
	*)	pecan_test_default= ;;
	esac

	# make
	: ${pecan_test_makefile:=${pecan_build_makefile}}
}

pecan_make_test_default()
{
	( cd "${pecan_test_srcdir}" &&
	  make -f "${pecan_test_makefile}" ${pecan_test_target} )
}

pecan_do_test()
{
	pecan_action_generator test
}
